### PR TITLE
Log Streaming

### PR DESCRIPTION
**Pull request by jdwall**
**Known Limitations:**

- ~~Port Selection is not an option, by default it runs on `9001`.~~ Non-issue due to no port conflict.
- There is not an opportunity to change the logs selected after-the-fact easily unless you edit the symlinks or modify `/etc/rc.local`
- ~~I need to make sure that, using sed, that if the value exists in `/etc/rc.local` that it does not continue to add the line over and over.)~~
- On mobile, log streaming does not scroll well.

**To Do:**

- Color code log files, beyond that of just `errors` being red.
- Add option when installing to choose whether you want the interface to have the search bar or not. By default, it does not.

**Features:**

- Integrated [frontail](https://github.com/mthenw/frontail) into the admin interface, by default, and then as an option in the user portal.
- Updated the settings to make sure that the upgrade process goes smoothly (double check me on the XML/SQLite implementation of the settings portion, I only use remote MySQL).
- Verify that node & npm are the correct versions, if not, install (node) or build from source (npm).
- Correctly identify which services (dump1090, dump978, pfclient, piaware, etc) are options for logging

**Visual:**

Admin Settings

Admin

User Portal

User Portal

### CODE REVIEW

**Comment by jprochazka** [comment]
First off this looks great!
Liking what I see so far.

> Port Selection is not an option, by default it runs on 9001. 

This port does not conflict with anything installed that I know of.

> There is not an opportunity to change the logs selected after-the-fact easily unless you edit the symlinks or modify /etc/rc.local 

Is it possible to monitor multiple logs at the same time? If so depending on what is installed could we specify all logs pertaining to what has been installed during the setup process using a bash script?

A little off topic but If it can report multiple logs can they be split up say place piaware's log on one tab and fr24feed on another?

> I need to make sure that, using sed, that if the value exists in /etc/rc.local that it does not continue to add the line over and over.

The following should look to see if a line exists in the /etc/rc.local file and add it to the end of the file before the line `exit 0`. This is used in a couple places in the bash scripts already.

LINETOFIND="Change to your lines contents."
LINENUMBER=($(sed -n '/exit 0/=' /etc/rc.local))
((LINENUMBER>0)) && sudo sed -i "${LINENUMBER[$((${#LINENUMBER[@]}-1))]}i $LINETOFIND\n" /etc/rc.local

**Comment by jdwall** [comment]
**Port Selection** - Yeah, I doubt that anyone will need to make any changes. 

**Monitor Multiple Log Files** - Yes, but they must be wildcards. So, there is not a way, to my knowledge, to have tabs for each log file. However, I do think that there could be a way to do php `exec()`, but, I am not entirely sure if that's the best way about it. In that scenario, we'd be stopping `frontail` and then manipulating the argument passed to `frontail`. 

**Installation Steps** - I guess it would help if I also let you know that the selection piece is built into the `adsb_logs.sh` script. The user is prompted by a whiptail to specify which files they want to log. If something does not exist, i.e. for me `dump978` the option is not provided.

Whiptail

FullInstallPrompt

The installer then symlinks the respective files (i.e. `/var/log/piaware.log`) to a folder it creates which is `/home/pi/adsb-receiver/logs/`. Then, frontail is passed the argument to tail all files that are in `/home/pi/adsb-receiver/logs/*`. 

**rc.local** - Thanks for the help when handling `/etc/rc.local`. I made commit [98868977633f52e7a726f2f3dc1a4f53e2910f77](https://github.com/jprochazka/adsb-receiver/pull/228/commits/98868977633f52e7a726f2f3dc1a4f53e2910f77) which resolves that piece.

**Comment by jprochazka** [comment]
FYI I will be keeping the 2.2.1 branch open and updated until this change is completed and merged.

**Comment by jdwall** [comment]
Sorry, I am not sure I fully understood when you said:

> Unless you have already merged your changes into another branch. 

Would it be helpful for you if I change the requested branch to merge with into `master`? If so, you're A-OK doing that. 

By the way, in terms of handling which log files this feature tails, do you have any ideas on how to build the ability for someone to, from the web interface, select the log file versus _just_ at the installation? That's the one piece about this feature that I'm working on that I just don't like and can't figure out how to get around it. Any and all help would be appreciated.

**Comment by jprochazka** [comment]
> Sorry, I am not sure I fully understood when you said:

Just saying even though I merged the 2.2.1 branch I did not delete it being that is where you are working on this. You can either continue to request to merge these changes into the 2.2.1 branch or if you want change it to merge into the 2.4.0 branch which will contain additions which will become v2.4.0 which will be the next version released.

> By the way, in terms of handling which log files this feature tails, do you have any ideas on how to build the ability for someone to, from the web interface, select the log file versus just at the installation?

I came across this doing a quick search.
https://github.com/taktos/php-tail
Maybe you can gather some ideas from that?

My receiver is not running super stable but if you catch it at the right time you can see an example here:
http://adsbreceiver.duckdns.org/logs.php#fr24feed.log

**Comment by jdwall** [comment]
Well, dang that makes it seemingly _really_ easy versus `frontail`. That eliminates `node` as a dependency. Plus, I like the dropdown. 

Would it be simpler to abandon this PR and just integrate `php-tail` then?

**Comment by jprochazka** [comment]
Something like that would probably would cut back on system overhead especially on RPi devices. You have more experience with this subject. I will leave that up to you and if you feel frontail would be a more robust solution or not.

**Comment by jdwall** [comment]
I didn't find that frontail used that much in resources, but, to be honest... if all we're losing is the search functionality then I'd much rather go the route of which you have proposed. I'll read up on it and give it a whirl on my side.

**Comment by jprochazka** [comment]
Let me know.

**Pull request closed without merging**
