### PR TITLE
Read history files instead of aircraft.json upon notification of file

### PR DESCRIPTION
**Pull request by adamkaplan**
creation from the kernel. This is more efficiant than polling and
appears to occur exactly every 30 seconds.

### _Do Not Merge_
This change requires the setup script to install the PyInotify package (https://github.com/dsoprea/PyInotify). I'm not sure how you want to handle this.. `pip`, source, or otherwise. I installed via:
```
sudo apt-get install python-pip
sudo pip install notify
```

### Notes
The script watches the logging directory and receives events from the operating system when anything happens. It ignores all events except "file moved to" which lets us know that some file was moved to the given file name. Based on observation, dump1090-mutability writes a new `history_XXX` file every 30 seconds. It doesn't actually rename `aircraft.json`, but rather appears to writes the history file using an "atomic write" procedure (i.e. writes to a temp file like `history_XXX.json.23abc5` and then renames that to `history_XXX.json`. I watch for this operation. A further safety optimization could be to check specifically for the "file moved from" event, and check that it is actually a history temp file – but I think that is overkill...

### CODE REVIEW

**Comment by adamkaplan** [comment]
Over about a minute of manual polling of the database, I confirmed that change triggers processing of messages on a cadence of 30 seconds.

```
sqlite> select max(time) from adsb_positions;
2016/06/09 03:35:56           <----
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:26           <----
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:26
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:26
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:26
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:26
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:26
sqlite> select max(time) from adsb_positions;
2016/06/09 03:36:56           <----
```

**Comment by adamkaplan** [comment]
system-localhost-disk_io_iops-7d

Initial results of this PR for the morning flight collection. It shows that I/O Ops have dropped nearly in half. This aligns with expectations since `flights.py` currently executes every 15 seconds (4x/min), and with this PR, executes once per history-file-roll create event, or every 30 seconds (2x/min).

**Comment by jprochazka** [comment]
SO what you need is python-pip added as a required package to the portal setup scripts in order for your changes to work correct?

**Comment by adamkaplan** [comment]
Technically it only needs PyInotify installed and usable, regardless of how it gets there. Pip is one option that works.

**Comment by jprochazka** [comment]
Sorry about that meant you needed python-pyinotify required. This has been done with commit 77b4a69586ea0bae539cf04d8d1d299dc716c45c. If this is the right package and all you needed I will go ahead and merge the pull request.

**Comment by adamkaplan** [comment]
Cool! 👍

**Comment by jprochazka** [comment]
Thanks again for the contribution.

The changes were added to the 2.2.1 branch and will be part of the next release. I wasn't able to merge the changes via the Merge Pull Request button easily due to all the changes which were made since the request was made so to make life easier I brought over the contents manually.

Commit 7fa44bd33107cc4a97f4437433e950936cd88c85 contains all the changes pertaining to this request.

**Pull request closed without merging**
