### PR TITLE
Add option parsing to install.sh with --help and --verbose options

### PR DESCRIPTION
**Pull request by Romeo-Golf**
Add option parsing to install.sh and surpress the "Press enter to continue" dialogs unless install.sh is called with the new -v|--verbose options

As discussed in https://github.com/jprochazka/adsb-receiver/issues/251

### CODE REVIEW

**Comment by Romeo-Golf** [comment]
Hopefully all done with changes to my 2.6.0 branch and, while I don't think I have broken anything, it would definitely be worth you reviewing and testing my changes :)

**Comment by jprochazka** [comment]
I had to move the main contents of install.sh to a new file called bash/init.sh which now contains the contents of what was previously known as install.sh. The file install.sh now handles the processing of "flags" such as displaying a help message and enabling logging at this time. 

You will notice 2 new options/flags which would pertain to your merge request which will need to be addressed. The following should fix the major conflict which exists with the install.sh file.

Revert any changes made to install.sh.

Any references to...
`if [ ${VERBOSE} ] ; then`
should be changed to...
`if [ $ADSB_UNATTENDED = "true" ] ; then`

Commits effecting  this request from oldest to newest if you wish to reference them:

commit 6149b1948056812f3f5b57962139ffb09db91cb8 
commit e88b12e6a6bcae672adb3ac54cd482c73e388608
commit 31e8c287a5acbbd5c5a109c58af831c5651c02fd

Note that the process is not set in stone yet and may change but this should be enough to get your request merged into the 2.6.0 branch cleanly.

**Comment by Romeo-Golf** [comment]
Joe,

Thanks for the update, comments and commits ;)

I have merged your changes back into my 2.6.0 branch so should be a clean merge back, but with a couple of points to consider:

Your changes to install.sh introduce 'ADSB_UNATTENDED' whereas the example.config file already has AUTOMATED_INSTALLATION_ENABLED="false" ... any objections to me sticking with whats already int the config?

I have kept the usage as a function above the case, this allows the command reference to be printed either if the user asks for it with --help or if they use an invalid command

The means of parsing the config file name from the CLI was interesting, but perhaps cleaner to use shift 2 to allow this to be specified as '-c <FILE>' or '--config--file <FILE>'  ?

Finally while the VERBOSE flag cam from my desire to speed up the install ahead of a fully unattended install, hence my changes were so that unless VERBOSE is set the many 'press enter to continue..' dialogues are surpressed...    

I had first considered if they could simply be removed all together, but figured there could be use cases such as during the first time install... hence the VERBOSE flag is not set unless enabled by the CLI switch or during first install if the image.sh script is present.  does that make sense?

**Comment by Romeo-Golf** [comment]
Also are you happy for us to aim towards using double square brackets for tests and to make the variables a bit more human readable with underscores where there would normally be spaces?

The latter came as a result of thinking I had gone mad after failing to spot that I had $RECEIVERLATITUDE when I should have had $RECEIVERALTITUDE, which I only spotted when I revised them to be $RECEIVER_LATITUDE and #RECEIVER_ALTITUDE  :)

**Comment by jprochazka** [comment]
I am not that concerned about the use of double brackets being they are ran most all the time in a bash shell. Generally I use single brackets out of force of habit when having to write scripts which were posix shell compliant. I am sure you have noticed both peppered throughout the scripts.

I am fine with the use of `_` in variable names.

**Comment by Romeo-Golf** [comment]
Thanks Joe, I figured as there were a few double brackets already I wuld try to use them for any of my changes, but as im a big fan of consistency id be tempted to try to replace all the single brackets at least on the smaller files like the decoder installs..

Similarly for the variable names while it was largely the LAT/LON/ALT that it would be most relevant to, I will try follow this with any new variables I introduce for the RTLSDR-OGN decoder and the related code which will allocate tuners to specific decoders ;)

Lastly I assume your happy with the PFclient version bump, which thanks to your strcucture of having only the version number in the variables.sh was nice and easy to update!

**Comment by Romeo-Golf** [comment]
I have manually merged the majority of your change into my 2.6.0, including a fix for the following:

**LOGFILE**="$LOG_DIRECTORY/install_$(date +"%m_%d_%Y_%H_%M_%S").log"
$BASH_DIRECTORY/init.sh 2>&1 | tee -a "$**LOG_FILE**"
CleanLogFile "$**LOG_FILE**"

**Comment by Romeo-Golf** [comment]
The only thing I havent got my head round yet, and thus havent merged, is the -c and --config-file options..

Is it not more common to use the format "-c <FILE>" and "--config-file <FILE>" than to require it in the form "--config-file=<FILE>"  ?

**Comment by jprochazka** [comment]
Figured I should go over these as well.

> Your changes to install.sh introduce 'ADSB_UNATTENDED' whereas the example.config file already has AUTOMATED_INSTALLATION_ENABLED="false" ... any objections to me sticking with whats already int the config?

That variable will be removed from the example configuration file with the introduction of the -u flag. Originally I was thinking that if the file was present an unattended install would automatically kick off. This would cause nothing but issues however if the file exists and someone were to simply want to add a feature.

> The means of parsing the config file name from the CLI was interesting, but perhaps cleaner to use shift 2 to allow this to be specified as '-c ' or '--config--file ' ?

What was present yesterday in the repository was slapped together before calling it a day as a placeholder/example of where the data would be collected and was by no means complete. I have modified the script into a useable form this morning. both -c and --config-file= will now work properly in install.sh.


> Finally while the VERBOSE flag cam from my desire to speed up the install ahead of a fully unattended install, hence my changes were so that unless VERBOSE is set the many 'press enter to continue..' dialogues are suppressed...

Thinking about it the -u/unattended flag will be changed to -a/--automated due to the fact dump1090-mutability and the Flightradar24 client require input. This means there cannot be any truly "unattended" installation option. This being said the variable `ADSB_UNATTENDED` will be changed to `ADSB_AUTOMATED_INSTALL`. This wording may change before release not sure yet.

Anyways I thought about verbose as well. If I were told verbose or not verbose I would expect that by setting verbose I would see all that is happening on my monitor as it is happening. By not setting this flag I would expect the display to contain very minimal information pertaining to what is going on.

At the moment I have no intensions of not displaying the script actions and compiler output to the user. So a verbose non-verbose option would not fit.

> Is it not more common to use the format "-c " and "--config-file " than to require it in the form "--config-file=" ?

Just going off of what is standard here when expecting a variable after a GNU long option. If you run the command `nano --help` or most any other program which takes variables in the command you will see most use `--something=<this>` as the format. Either of these are expectable at this time:

`./install.sh -l -a -c /home/pi/adsb-receiver/installation.config`

`./install --log-output --automated --config-file=/home/pi/adsb-receiver/installation.config`

**Comment by jprochazka** [comment]
BTW I have been working on install.sh a bit finishing up the -a and -c options I will try and hold off on any more changes to this file until you get your merge in.

**Comment by Romeo-Golf** [comment]
Cheers, should be able to finish my merge in the next few hours and finally stop fiddling with 2.6.0 :)

Thanks for explaining the -c/--config-file options and happy with any means of specifying the config file that work so will merge that bit in with the rest of that change.

In terms of the automated/unattended it may be useful to consider that my original use case was to be able to do an unattended re-install a.k.a an update of the adsb-receiver code itself and any of the feeders/decoders/extras as could be done without user input.. the idea being to run it from cron, but happy for you to call this whatever you think appropriate.

Finally for what is currently the 'VERBOSE' flag again i dont mind what its call, i just wanted a way to supress the multitude of press enter to continue dialogs which significantly slowed down the current manual update process, mostly to make testing any changes i make somewhat less tedious..

And as mention having thought first about just removing them I figured they probably are useful at least during the first run of the install, hence moved the various 'read -p' lines so that they only run if this flag is   set to true... but if you want to call the flag/variable something else then feel free :)

**Comment by jprochazka** [comment]
Problem is there cannot be a truly "unattended" installation option available. Due to the way some of the 3rd party applications which are available for install. There are currently two applications which require user intervention which cannot be circumvented.

Currently dump1090-mutability requires you to specify whether or not it should start automatically.
https://github.com/mutability/dump1090/issues/168

And the Flightradar24 client when installed on an ARM device requires it's own setup options to be entered in manually.

**Comment by Romeo-Golf** [comment]
yay, after having manually merged the changes I eventually managed to convince github to acknowledge this and we are back to this pull request being a clean merge against your 2.6.0 branch..

Some comments:

- The usage is above the case for reasons explained above
- I think shift 2 is cleaner way of taking the config file from the -c option, but have left the --config-file as it
- Some variables didnt match, such as 'ADSB_ADSB_AUTOMATED_INSTALL' but suspect these were jsut search and replace issues 
- Finally I have left the verbose flag in there, mostly as i find it useful for these to be surpressed by default when testing the changes.. but happy for this to go once everything but the feeders which require user input can be run unattended ;)

Thanks

**Pull request merged**
