### PR TITLE
MLAT Client Version has changed

### PR DESCRIPTION
**Pull request by IXEguy**
Installation failed due to script checking for 0.2.6. Checked the build directory and noticed it was now 0.2.9.

Updated MLATCLIENTVERSION & MLATCLIENTTAG in variables.sh & it installed correctly.

### CODE REVIEW

**Comment by Romeo-Golf** [comment]
FYI this is covered by an existing issue and awaiting @jprochazka to approve a pull request that updates the MLAT client and resolves a number of other user reported issues...

**Comment by IXEguy** [comment]
Thanks for the message. I noticed your pull request with the same changes
when I checked back on this a month or two ago.

I'll try and see if I can cancel this pull request.

**Comment by Romeo-Golf** [comment]
@jprochazka 

This pull request is duplciated by #342, so if that is accepted then this can be closed.

**Comment by IXEguy** [comment]
Closing pull request as it is superceded by others (#342 & #310 )

**Pull request closed without merging**
